<article id="privileges" class="page">
    <header>
        <h1>Editar Privilégio</h1>
    </header>

<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('acl-admin/default',array('controller'=>'privileges','action'=>'edit')));

$form->prepare();
echo $this->form()->openTag($form);

echo "<fieldset><legend>Altere o formulário abaixo.</legend>";
$formContent="";
foreach ($form as $element){
        $formContent .= "\n<div class=\"pure-controls\">".$this->formrow($element);
        if(strpos($this->formrow($element), "type=\"submit\"")>0){
                $formContent .= " <a href=\"". $this->url('acl-admin/default',array('controller'=>'privileges')) ."\" class=\"pure-button button-secondary\">Cancelar</a>";
        }
        $formContent .=  "</div>";
        
}
echo $formContent;
echo "</fieldset>";
echo $this->form()->closeTag();

?>
</article>