<article id="usuarios" class="page">
    <header>
        <h1>Novo Usuário</h1>
    </header>
<?php
$form = $this->form; 

$form->setAttribute('action', $this->url('admin-admin/default',array('controller'=>'usuarios','action'=>'new')));

$form->prepare();
echo $this->form()->openTag($form);

echo "<fieldset><legend>Preencha o formulário para cadastrar.</legend>";
$formContent="";
foreach ($form as $element){
        $formContent .= "\n<div class=\"pure-controls\">".$this->formrow($element);
        if(strpos($this->formrow($element), "type=\"submit\"")>0){
                $formContent .= " <a href=\"". $this->url('admin-admin/default',array('controller'=>'usuarios')) ."\" class=\"pure-button button-secondary\">Cancelar</a>";
        }
        $formContent .=  "</div>";
        
}
echo $formContent;
echo "</fieldset>";
echo $this->form()->closeTag();

?>
</article>