<?php

use Base\Mib\URL,
    Base\Mib\DataHora;

$configs = $this->Configger();

?>

Olá <?php echo $this->nome;?>,
<br />
<br />

<p>
    Foi pedido a redefinição de senha para o seu e-mail em nosso site <?= $configs['sistema']['nome'] ?>.
    <br />
    Para ativar sua conta e definir uma nova senha, acesse: http://<?php echo URL::getInstance()->getHost() . $this->url('admin-activate', array('key'=>$this->activationKey)); ?>
    
</p>
<br />
<p>
    Observação: caso não tenha solicitado redefinição de senha, favor desconsiderar a mensagem. Pode ter sido alguém que digitou seu e-mail por engano e sem a confirmação com o link acima, não poderá acessar.
</p>
<br />
<p>
    Em caso de dúvidas, entre em contato conosco pela seção Fale Conosco de nosso site.

    http://<?php echo URL::getInstance()->getHost() ?>/faleconosco
</p>
<br />
<hr />
Página de Referência: <?php echo $_SERVER['HTTP_REFERER']; ?> <br />
Data de envio: <?php echo DataHora::dataExtenso() . " - " . DataHora::horaExtenso(); ?>
<hr />