<?php

use Base\Mib\URL,
    Base\Mib\DataHora;

$configs = $this->Configger();

?>

Olá <?php echo $this->nome;?>,
<br />
<br />

<p>
    Foi feito um pedido de login, com o seu CPF, em nosso site <?= $configs['sistema']['nome'] ?>.
    <br />
    Para entrar utilize a senha: <strong><?php echo $this->senha; ?></strong>
    
</p>
<br />
<p>
    Observação: caso não tenha solicitado o login, favor desconsiderar a mensagem. Pode ter sido alguém que digitou seu CPF por engano e sem acesso a este e-mail, não irá conseguir entrar.
</p>
<br />
<p>
    Em caso de dúvidas, entre em contato conosco pela seção Fale Conosco de nosso site.

    http://<?php echo URL::getInstance()->getHost() ?>/faleconosco
</p>
<br />
<hr />
Página de Referência: <?php echo $_SERVER['HTTP_REFERER']; ?> <br />
Data de envio: <?php echo DataHora::dataExtenso() . " - " . DataHora::horaExtenso(); ?>
<hr />