<article id="cadastro" class="page">
    <header>
        <h1>Processo seletivo de contratos</h1>
        <h2>identificação requirida</h2>
    </header>
    <div class="pure-g">
        <div class="pure-u-1 pure-u-md-1-2">
<?php

$configs = $this->Configger();

echo $this->flashMessenger()->renderCurrent('error');
echo $this->flashMessenger()->renderCurrent('success');
echo $this->flashMessenger()->renderCurrent('info');
echo $this->flashMessenger()->renderCurrent('warning');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('default');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('error');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('success');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('info');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('warning');

$form = $this->form;
$form->setAttribute('action',$this->url('admin-auth'));
$form->prepare();

echo $this->form()->openTag($form);

echo "<fieldset><legend>Preencha o formulário para se identificar</legend>";
$formContent="";
foreach ($form as $element)
        $formContent .= "\n<div class=\"pure-controls\">".$this->formrow($element) . "</div>";
echo $formContent;
echo "</fieldset>";

echo $this->form()->closeTag();

?>
            <a href="<?= $this->url('admin-email'); ?>" class="pure-button button-warning">Problemas ao entrar?</a>
        </div>
        <div class="pure-u-1 pure-u-md-1-2">
            <h3>Cadastro</h3>
                <ul class="listadelinks">
                    <li><a href="<?= $this->url('admin-register'); ?>" class="pure-button button-success">Cadastre-se</a></li>
                </ul>
<?php
    if($configs['usaprovedorsocial'])
                \Base\Mib\Layout::menuSocial($this->url('admin-social',array('controller'=>'auth','action'=>'social')));
?>
            </div>
        </div>
</article>