<article id="conta" class="page">
    <header>
        <h1>Cadastro de Endereço</h1>
    </header>

    <?php
    $form = $this->form;

    $form->setAttribute('action', $this->url('admin-admin/default', array('controller' => 'conta', 'action' => 'endereco')));

    $form->prepare();
    echo $this->form()->openTag($form);
    ?>
    <fieldset>
        <legend>Altere o formulário abaixo.</legend>
        <div class="pure-controls">
            <hr>
            <label>
                Buscar endereço:<br />
                <input type="text" id="enderecooucep" placeholder="Endereço ou CEP">
            </label> <input type="button" value="buscar" id="buscarendereco" class="pure-button pure-button-primary">
            <div id="buscarenderecoresultado">
                <p>Digite acima o endereço, ou parte dele, ou o CEP e clique em buscar. As ruas encontradas serão mostradas aqui. </p>
                <p>Com as ruas encontradas, clique na que for o seu endereço. Caso não encontre o endereço, forneça ele no campo "complemento".</p>
            </div>
            <hr>
        </div>
        <?php
        $formContent = "";
        foreach ($form as $element) {
            $formContent .= "\n<div class=\"pure-controls\">" . $this->formrow($element);
            if (strpos($this->formrow($element), "type=\"submit\"") > 0) {
                $formContent .= " <a href=\"" . $this->url('admin-admin/default', array('controller' => 'conta')) . "\" class=\"pure-button button-secondary\">Cancelar</a>";
            }
            $formContent .=  "</div>";
        }
        echo $formContent;
        echo "</fieldset>";
        echo $this->form()->closeTag();

        ?>
</article>