<article id="conta" class="page">
    <header>
        <a href="<?= $this->url('admin-admin'); ?>" class="pure-button pure-button-primary"><i class="fa fa-arrow-left"></i> Painel Administrativo</a>
        <h1>Cadastro</h1>
    </header>
<?php

$configs = $this->Configger();

echo $this->flashMessenger()->renderCurrent('error');
echo $this->flashMessenger()->renderCurrent('success');
echo $this->flashMessenger()->renderCurrent('info');
echo $this->flashMessenger()->renderCurrent('warning');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('default');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('error');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('success');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('info');
$this->flashMessenger()->clearCurrentMessagesFromNamespace('warning');

$entity = $this->usuario;

?>
        <div class="pure-g">
            <div class="pure-u-1-4">
                <p>
                Foto de Perfil:<br />
                <a href="<?php echo $this->url('admin-admin/default',
                        ['controller' => 'conta','action' => 'imagemperfil']); ?>" style="background-image: url(<?php
                    $dirImg = $this->basePath('img/fotos/perfil/');
                    $imgUsuario = $dirImg.$entity->getId().".jpg";
                    if(is_file($_SERVER["DOCUMENT_ROOT"]."/".$imgUsuario)){
                        echo $imgUsuario;
                    }else{
                        echo $dirImg."semfoto.jpg";
                    }
                    ?>);" class="fotoperfil"><span>Alterar foto</span></a>
                </p>
            </div>
            <div class="pure-u-3-4">
                <table class="pure-table responsivo">
                    <caption>Dados principais:</caption>
                    <tbody>
                        <tr class="pure-table-odd">
                            <th id="nomeexibicao">Nome de Exibição</th>
                            <td headers="nomeexibicao">
                                <?php echo $entity->getNomeExibicao(); ?>
                            </td>
                        </tr>
                        <tr>
                            <th id="principaisnome">Nome</th>
                            <td headers="principaisnome">
                                <?php echo $entity->getNome(); ?>
                            </td>
                        </tr>
                        <tr class="pure-table-odd">
                            <th id="principaissnome">Sobrenome</th>
                            <td headers="principaissnome">
                                <?php echo $entity->getSNome(); ?>
                            </td>
                        </tr>
                        <tr>
                            <th id="principaisemail">Email</th>
                            <td headers="principaisemail">
                                <?php echo $entity->getEmail(); ?>
                            </td>
                        </tr>
                    </tbody>
                    <tfooter>
                        <tr class="pure-table-odd">
                            <th id="principaisacao">Ação</th>
                            <td headers="principaisacao">
                                <a href="<?php echo $this->url('admin-admin/default',
                        ['controller' => 'conta','action' => 'edit']);?>" class="button-secondary pure-button">Editar</a>

                            <a href="<?php echo $this->url('admin-admin/default',
                ['controller' => 'conta','action' => 'password']);?>" class="pure-button">Redefinir senha</a>

                                <a href="<?php echo $this->url('admin-admin/default',
                        ['controller' => 'conta','action' => 'delete']);?>" class="button-warning pure-button">Excluir conta</a>

                            </td>
                        </tr>
                    </tfooter>
                </table>
            </div>
            <div class="pure-u-1-2">
                <table class="pure-table responsivo">
                    <caption>Telefones:</caption>
                    <thead>
                        <tr>
                            <td colspan="2">
                                <a href="<?php echo $this->url('admin-admin/default',array('controller'=>'conta','action'=>'telefone')); ?>" class="pure-button pure-button-primary">Novo</a>
                            </td>
                        </tr>
                        <tr>
                            <th id="telefone">Telefone</th>
                            <th id="telefoneacao">Ação</th>
                        </tr>
                    </thead>
                    <tbody><?php 


                    if($entity->getTelefones()->count()<1){
                        ?>
                            <tr class="pure-table-odd">
                                <td colspan="2">Não há telefones cadastrados!</td>
                    <?php
                    }else{
                        foreach($entity->getTelefones() as $telefone){

                        ?>
                        <tr class="pure-table-odd">
                            <td headers="telefone" data-label="Telefone: ">
                                <?php echo $telefone->getTelefone(); ?>
                            </td>
                            <td header="telefoneacao" data-label="Ação: ">
                                <a href="<?php echo $this->url('admin-admin/default',
                        ['controller' => 'conta','action' => 'telefone','id'=>$telefone->getId()]);?>" class="button-secondary pure-button">Editar</a>
                                <a href="<?php echo $this->url('admin-admin/default',
                        ['controller' => 'conta','action' => 'deletetelefone','id'=>$telefone->getId()]);?>" class="button-warning pure-button">Excluir</a>
                            </td>
                        </tr><?php

                        }
                    }
                        ?>
                    </tbody>
                </table>
            </div>
            <div class="pure-u-1-2">
                <table class="pure-table responsivo">
                    <caption>Endereço:</caption>
                    <thead>
                        <tr>
                            <td colspan="2">
                                <a href="<?php echo $this->url('admin-admin/default',array('controller'=>'conta','action'=>'endereco')); ?>" class="pure-button pure-button-primary">Novo</a>
                            </td>
                        </tr>
                        <tr>
                            <th id="endereco">Endereço</th>
                            <th id="enderecoacao">Ação</th>
                        </tr>
                    </thead>
                    <tbody><?php 

                    foreach($entity->getEnderecos() as $endereco){

                    ?>
                        <tr class="pure-table-odd">
                            <td headers="endereco" data-label="Endereço: ">
                                <?php echo $endereco->getEndereco()->getAddress(). ", " . $endereco->getNumero() . (!empty($endereco->getNome()) ? " (".$endereco->getNome() . ")" : ""); ?>
                            </td>
                            <td header="enderecoacao" data-label="Ação: ">
                                <a href="<?php echo $this->url('admin-admin/default',
                        ['controller' => 'conta','action' => 'endereco','id'=>$endereco->getId()]);?>" class="button-secondary pure-button">Editar</a>
                                <a href="<?php echo $this->url('admin-admin/default',
                        ['controller' => 'conta','action' => 'deleteendereco','id'=>$endereco->getId()]);?>" class="button-warning pure-button">Excluir</a>
                            </td>
                        </tr><?php

                    }

                    if($entity->getEnderecos()->count() < 1){
                    ?>
                        <tr class="pure-table-odd">
                            <td colspan="2">Não há endereços cadastrados!</td>
                    <?php
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        <?php

            if($configs['usaprovedorsocial']){

        ?>
            <div class="pure-u-1">
                <table class="pure-table responsivo">
                    <caption>Provedores de Acesso:</caption>
                    <thead>
                        <tr>
                            <th id="provedorprovedor">Provedor</th>
                            <th id="provedoremail">E-mail</th>
                            <th id="provedorperfil">Perfil</th>
                            <th id="provedoracao">Ação</th>
                        </tr>
                    </thead>
                    <tbody>
        <?php
        
                $i = 0;
                foreach($entity->getSociais() as $social):
                $i++;

        ?>
                        <tr<?php
        
        if($i%2==0)
            echo " class=\"pure-table-odd\"";

        ?>>
                            <td headers="provedorprovedor" data-label="Provedor: ">
                                <?php echo $social->getOauthProvider(); ?>
                            </td>
                            <td headers="provedoremail" data-label="E-mail: ">
                                <?php echo $social->getEmail(); ?>
                            </td>
                            <td headers="provedorperfil" data-label="Perfil: ">
                                <?php echo $social->getOauthProfile(); ?>
                            </td>
                            <td header="provedoracao" data-label="Ação: "><a href="<?php echo $this->url('admin-admin/default',
                        array('controller'=>'conta','action'=>'deletesocial','id'=>$social->getOauthUid()));?>" class="button-warning pure-button">Excluir</a></td>
                        </tr>
        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="4" style="text-align:center;">
                            Adicionar Provedor: 
                            <?php \Base\Mib\Layout::menuSocial($this->url('admin-social',array('controller'=>'auth','action'=>'social'))); ?>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <?php
             
                }
                
            ?>
        </div>
</article>