	
	<article id="topicosdapoliticadeprivacidade" class="page">
		<header>
			<h1>Tópicos da Política de Privacidade</h1>
			<p>
				Aqui você poderá ver os principais tópicos do texto e clicar para ir direto ao de seu interesse.
			</p>
			<p>SME = Secretaria Municipal de Educação - Rio de Janeiro
				<br />
			</p>
			<p>
				CIT = Centro de Inovação Tenológica
			</p>
		</header>
		<ul>
			<li>
				<a href="#politicadeprivacidade">Política de Privacidade</a>
				<ul>
					<li>
						<a href="#informacoescoletadas">Informações que coletamos</a>
					</li>
					<li>
						<a href="#comousamosinformacoescoletadas">Como usamos as informações que coletamos</a>
					</li>
				</ul>
			</li>
			<li>
				<a href="#transpareciaeescolha">Transparência e escolha</a>
			</li>
			<li>
				<a href="#informacoesqueousuariocompartilha">Informações que o usuário compartilha</a>
			</li>
			<li>
				<a href="#acessoeatualizacaodesuasinformacoes">Acesso e atualização de suas informações pessoais</a>
			</li>
			<li>
				<a href="#informcoesquecompartilhamos">Informações que compartilhamos</a>
			</li>
			<li>
				<a href="#quandoestapoliticadeprivacidadeseaplica">Quando esta Política de Privacidade se aplica</a>
			</li>
			<li>
				<a href="#compilanceecooperacaocomasautoridadesreguladoras">Compliance e cooperação com as autoridades reguladoras</a>
			</li>
			<li>
				<a href="#alteracoes">Alterações</a>
			</li>
			<li>
				<a href="#praticasespecificasdeproduto">Práticas específicas de produto</a>
			</li>
		</ul>
	</article>

	<article id="politicadeprivacidade" class="page">
		<header>
			<h1>Bem-vindo à Política de Privacidade do SME - CIT</h1>
			<p>
			Ao utilizar os nossos serviços, o usuário confia a nós as suas informações. Esta Política de Privacidade destina-se a explicar quais dados coletamos, por que os coletamos e o que fazemos com eles. Sabemos desta importância e por isso disponibilizamos o link deste documento em todas as nossas páginas. Lembrando que é possível encontrar os controles para gerenciar algumas informações e proteger a privacidade e segurança em 'Minha Conta'.
			</p>
		</header>
		<h2>Política de Privacidade</h2>
		<h4>Última modificação: 16 de Março de 2017</h4>
		<p>
			Estamos sempre criando formas de os usuários poderem estar usando os nossos serviços. E quando um usuário compartilha informações conosco, ao se cadastrar e se identificar em nosso site, podemos tornar esses serviços melhores. E sempre sendo claro quanto ao modo como estamos usando suas informações e ao modo como o usuário pode proteger sua privacidade.
		</p>
		<h4>Nossa Política de Privacidade explica:</h4>
		<ul>
			<li>Quais informações coletamos e por que as coletamos.</li>
			<li>Como usamos essas informações.</li>
			<li>As opções que oferecemos, incluindo o modo de acessar e atualizar informações.</li>
		</ul>
		<p>
			Em nossos documentos, tentamos ser o mais claro e explicativo possível. Mas caso não esteja familiarizado com termos tecnológicos e gostaria de aglum esclarecimento melhor, poderá entrar em contato consco, na seção <a href="../faleconosco">fale conosco</a> de nosso site. Inclusive isto poderá nos auxiliar a melhorar nossos textos.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="informacoescoletadas" class="page">
		<header>
			<h3>Informações que coletamos</h3>
		</header>
		<p>
			Coletamos informações para fornecer serviços melhores a todos os nossos usuários, de forma que estas podem nos ajudar a entender o que se procura em nosso site, gostos e até prever uma necessidade.
		</p>
		<p>
			Coletamos informações das seguintes maneiras:
		</p>
		<ul>
			<li>
				<strong>Informações que o usuário nos transmite.</strong> Alguns de nossos serviços, o usuário poderá realizar um cadastro ou interagir enviando mensagem ou participando de pesquisas de opinião em nosso site. Geralmente estas informações podem ser anônimas e quando não, recebemos o nome e e-mail para o caso de entrar em contato e ajudar em alguma questão. Também há possibilidade de nos informar diversas outros dados, onde é criado um perfil e facilitando a destinar conteúdos de interesse.
			</li>
			<li>
				<strong>Informações que coletamos a partir do uso que o usuário faz dos nossos serviços.</strong> Poderemos coletar algumas informações sobre os serviços que o usuário utiliza e como o usa, de forma a identificar algum problema ou melhoria que precisa ser feita. Estas informações incluem:
				<ul>
					<li>
						<strong>Informações do dispositivo</strong><br />
						Coletamos informações específicas de dispositivos, como: configuração, modelo, tipos, sistemas, rede de internet usada, navegador, identificação na internet e entre outras para assim entendermos melhor o nosso público e adaptar os nossos serviços para serem acessados da melhor forma.
					</li>
					<li>
						<strong>Informações do local</strong><br />
						Podemos coletar informações do local do usuário para poder gerar estatísticas de uso e alcance de nossos serviços. E quando for possível, poderemos oferecer conteúdos que melhor atenda uma determinada localidade.
					</li>
					<li>
						<strong>Cookies e tecnologias semelhantes</strong><br />
						Para a comodidade de nossos usuários, em alguns serviços poderemos utilizar tecnologias que armazenam algumas opções do usuário com o nosso site. Desta forma poderemos ter opções de o usuário já entrar no site e se identificar automáticamente ou o conteúdo ser visualizado da forma que foi escolhida anteriormente.
					</li>
				</ul>
			</li>
		</ul>
		<p>
			As informações que coletamos quando o usuário se identifica em nosso site ou serviços, além das informações do usuário que recebemos dos nossos parceiros, nós a tratamos como informações pessoais e garantiremos a privacidade da mesma. Toda informação pessoal, o usuário tem a opção de escolher se a mesma será pública ou privada, exibida só para ele, ou o não cadastramento da mesma.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="comousamosinformacoescoletadas" class="page">
		<header>
			<h3>Como usamos as informações que coletamos</h3>
		</header>
		<p>
			Usamos as informações para poder identificar o usuário no site, de forma que ao utilizar algum serviço o mesmo possa ter mensagens e conteúdos voltados para si. A opção do nome do usuário, estando visível por padrão, poderá ser exibida em conteúdos que o mesmo publicar no modo público. Exemplo: comentários, notícias e entre outros.
		</p>
		<p>
			Ao se cadastrar ou enviar e-mail de contato, podemos guardar as mensagens trocadas e o endereço de e-mail, afim de melhorar o nosso atendimento ou resolver problemas que venham a ser apresentados. Com o contato do usuário, poderemos enviar notificações de soluções, melhorias e novidades em nosso site. Mas o usuário também tem a opção de informar que não quer mais contato.
		</p>
		<p>
			Sempre iremos solicitar autorização antes de usar informações para outros fins que não os definidos nesta Política de Privacidade.
		</p>
		<p>
			Nosso site utiliza servidores que estão localizados em diversas partes do mundo. Podemos processar algumas informações pessoais do usuário em um servidor localizado fora do país em que este vive.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="transpareciaeescolha" class="page">
		<header>
			<h2>Transparência e escolha</h2>
		</header>
		<p>
			As pessoas têm diferentes preocupações sobre privacidade. Nosso objetivo é a clareza quanto às informações que coletamos, de modo que o usuário possa fazer escolhas importantes sobre como elas são usadas. Por exemplo, o usuário pode:
		</p>
		<ul>
			<li>
				<strong>Rever e controlar</strong> determinados tipos de informações ligados a sua conta em nosso site, sempre acessado pela opção 'Minha Conta'.
			</li>
			<li>
				<strong>Ajustar</strong> a forma como seu Perfil associado ao nosso site é mostrado a outras pessoas.
			</li>
			<li>
				O usuário pode escolher se o <strong>nome e a foto</strong> do perfil dele devem aparecer nas recomendações compartilhadas exibidas em anúncios.
			</li>
		</ul>
		<p>
			O usuário também pode configurar seu navegador para bloquear todos os cookies, inclusive cookies associados com nossos serviços, ou para indicar quando um cookie estiver sendo configurado por nós. Entretanto, é importante lembrar que muitos de nossos serviços podem não funcionar de maneira adequada se seus cookies estiverem desativados. Por exemplo, pode ser que não nos lembremos das preferências de visualização ou conteúdo.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="informacoesqueousuariocompartilha" class="page">
		<header>
			<h2>Informações que o usuário compartilha</h2>
		</header>
		<p>
			Alguns de nossos serviços são públicos, e por isto, quando o usuário cadastra ou envia informações, estas estarão públicas. Podendo ser indexadas por mecanismos de pesquisa e aparecer em sites de busca.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="acessoeatualizacaodesuasinformacoes" class="page">
		<header>
			<h2>Acesso e atualização de suas informações pessoais</h2>
		</header>
		<p>
			Sempre que o usuário usa nossos serviços, nosso objetivo é oferecer-lhe acesso a suas informações pessoais. Se essas informações estiverem erradas, nos empenhamos em prover maneiras rápidas de atualizá-las ou excluí-las – exceto quando temos de mantê-las para fins comerciais legítimos ou jurídicos. Ao atualizar suas informações pessoais, podemos solicitar o usuário que confirme sua identidade antes de atendermos a solicitação.
		</p>
		<p>
			Podemos recusar as solicitações que sejam repetitivas, que requeiram esforço técnico desproporcional (por exemplo, desenvolvimento de um novo sistema ou mudança fundamental de uma prática existente), coloquem em risco a privacidade de outros ou que sejam extremamente impraticáveis (por exemplo, solicitações referentes a informações localizadas em sistemas de backup).
		</p>
		<p>
			Nos casos em que pudermos fornecer acesso e correção de informações, faremos isso gratuitamente, exceto quando isso exigir esforço desproporcional. Nosso objetivo é manter nossos serviços de modo a proteger informações de destruição acidental ou maliciosa. Assim, depois de excluir informações de nossos serviços, não podemos excluir imediatamente cópias residuais de nossos servidores ativos e pode não ser possível remover informações de nossos sistemas de backup.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="informcoesquecompartilhamos" class="page">
		<header>
			<h2>Informações que compartilhamos</h2>
		</header>
		<p>
			Não compartilhamos informações pessoais com empresas, organizações e indivíduos externos à SME - CIT, salvo em uma das seguintes circunstâncias:
		</p>
		<ul>
			<li>
				<strong>Com sua autorização</strong>

				Compartilharemos informações pessoais com empresas, organizações ou indivíduos externos à SME - CIT quando tivermos sua autorização para isso. Solicitamos autorização (“opt-in” - <em>formulário de aceite digital</em>) para compartilhamento de quaisquer informações sensíveis de caráter pessoal.
			</li>
			<li>
				<strong>Para processamento externo</strong>

				Fornecemos informações pessoais a nossas afiliadas ou outras empresas ou pessoas confiáveis para processá-las para nós, com base em nossas instruções e em conformidade com nossa Política de Privacidade e quaisquer outras medidas de segurança e de confidencialidade adequadas.
			</li>
			<li>
				<strong>Por motivos legais</strong>

				Compartilharemos informações pessoais com empresas, organizações ou indivíduos externos à SME - CIT se acreditarmos, de boa-fé, que o acesso, uso, conservação ou divulgação das informações seja razoavelmente necessário para:
				<ul>
					<li>cumprir qualquer legislação, regulação, processo formal ou solicitação governamental aplicável.</li>
					<li>cumprir Termos de Serviço aplicáveis, inclusive investigação de possíveis violações.</li>
					<li>detectar, impedir ou abordar de alguma outra forma fraude, questões técnicas ou de segurança.</li>
					<li>proteger contra dano aos direitos, a propriedade ou a segurança da SME - CIT, nossos usuários ou o público, conforme solicitado ou permitido por lei.</li>
				</ul>
			</li>
		</ul>
		<p>
			Podemos compartilhar informações que não sejam pessoalmente identificáveis, de maneira anônima e que impossibilite a identificação, publicamente e com nossos parceiros, como sites de editores, anunciantes ou sites relacionados. Por exemplo, podemos compartilhar informações publicamente para mostrar tendências sobre o uso geral dos nossos serviços.
		</p>
		<p>
			Se a SME - CIT estiver envolvida em uma fusão, aquisição ou venda de ativos, continuaremos a garantir a confidencialidade de qualquer informação pessoal e avisaremos os usuários afetados antes que as informações pessoais sejam transferidas ou sejam submetidas a uma política de privacidade diferente.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="quandoestapoliticadeprivacidadeseaplica" class="page">
		<header>
			<h2>Quando esta Política de Privacidade se aplica</h2>
		</header>
		<p>
			Nossa Política de Privacidade se aplica a todos os serviços oferecidos pelo SME - CIT e suas afiliadas e serviços oferecidos em outros sites (por exemplo, nossa agenda e notícias), mas exclui serviços que tenham políticas de privacidade separadas que não incorporam esta Política de Privacidade.
		</p>
		<p>
			Nossa Política de Privacidade não se aplica a serviços oferecidos por outras empresas ou indivíduos, inclusive produtos ou sites que podem ser exibidos ao usuário pelo nosso site, sites que podem incluir serviços da SME - CIT, ou outros sites com links de nossos serviços. Nossa Política de Privacidade não abrange as práticas de informação de outras empresas e organizações que anunciam nossos serviços e que podem usar cookies, pixels tags e outras tecnologias para oferecer anúncios relevantes.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="compilanceecooperacaocomasautoridadesreguladoras" class="page">
		<header>
			<h2>Compliance e cooperação com as autoridades reguladoras</h2>
		</header>
		<p>
			Analisamos regularmente se mantemos a conformidade com a Política de Privacidade. Quando recebemos reclamações formais por escrito, entramos em contato com o autor da reclamação para acompanhamento. Trabalhamos com autoridades reguladoras apropriadas, inclusive autoridades locais de proteção de dados para resolver quaisquer reclamações referentes à transferência de dados pessoais que não podemos resolver diretamente com nossos usuários.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="alteracoes" class="page">
		<header>
			<h2>Alterações</h2>
		</header>
		<p>
			Nossa Política de Privacidade pode ser alterada de tempos em tempos. Nós não reduziremos os direitos do usuário nesta Política de Privacidade sem seu consentimento explícito. Publicaremos quaisquer alterações da política de privacidade nesta página e, se as alterações forem significativas, forneceremos um aviso com mais destaque (incluindo, para alguns serviços, notificação por e-mail das alterações da política de privacidade). Também manteremos as versões anteriores desta Política de Privacidade arquivadas para que o usuário possa visualizá-las.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
	<article id="praticasespecificasdeproduto" class="page">
		<header>
			<h2>Práticas específicas de produto</h2>
		</header>
		<p>
			Estas são as práticas que procuramos manter em todo o nosso site, produtos e serviços. Mas caso algum produto ou serviço, possua uma política específica, a mesma será informada nesta seção com um link para o documento.
		</p>
		<a href=#>Voltar ao Início</a>
	</article>
