<article id="cadastro" class="page">
    <header>
        <h1>Problemas ao entrar no Sistema</h1>
        <p>
            Ao realizar o cadastro, o seu login será feito através de e-mail válido. Caso tenha cadastrado um e-mail incorreto, este não será ativado e após uma hora, sem o acesso do link de ativação, o registro será apagado, permitindo uma nova tentativa.
        </p>
    </header>
<?php
// echo $this->flashMessenger()->renderCurrent('error');
// echo $this->flashMessenger()->renderCurrent('success');
// echo $this->flashMessenger()->renderCurrent('info');
// echo $this->flashMessenger()->renderCurrent('warning');
// $this->flashMessenger()->clearCurrentMessagesFromNamespace('default');
// $this->flashMessenger()->clearCurrentMessagesFromNamespace('error');
// $this->flashMessenger()->clearCurrentMessagesFromNamespace('success');
// $this->flashMessenger()->clearCurrentMessagesFromNamespace('info');
// $this->flashMessenger()->clearCurrentMessagesFromNamespace('warning');

// $form = $this->form; 

// $form->setAttribute('action', $this->url('admin-email'));

// $form->prepare();
// echo $this->form()->openTag($form);

// echo "<fieldset><legend>Para redefinir sua senha, informe o seu CPF e iremos lhe ajudar.</legend>";
// $formContent="";
// foreach ($form as $element){
//         $formContent .= "\n<div class=\"pure-controls\">".$this->formrow($element);
//         if(strpos($this->formrow($element), "type=\"submit\"")>0){
//                 $formContent .= " <a href=\"". $this->url('admin-auth') ."\" class=\"pure-button button-secondary\">Cancelar</a>";
//         }
//         $formContent .=  "</div>";
        
// }
// echo $formContent;
// echo "</fieldset>";
// echo $this->form()->closeTag();

?>
</article>